version: "2.1"

services:
    db:
        extends:
            file: base.yml
            service: db
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    web:
        extends:
            file: base.yml
            service: web
        build: 
            args:
                - DJANGO_ENV=dev
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./webapp:/webapp
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy
volumes: 
    dockerized_django_tutorial_data:
        external: true